# Generated by Django 3.0.8 on 2022-03-29 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name_place'],
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specie',
                'verbose_name_plural': 'Species',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(max_length=150)),
                ('phylum', models.CharField(max_length=150)),
                ('t_class', models.CharField(max_length=150)),
                ('t_order', models.CharField(max_length=150)),
                ('family', models.CharField(max_length=150)),
                ('genus', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_sighting_api.Specie')),
            ],
            options={
                'verbose_name': 'Taxonomic Category',
                'verbose_name_plural': 'Taxonomic Categories',
                'ordering': ['kingdom'],
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_sighting_api.Place')),
                ('id_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_sighting_api.Specie')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sighting',
                'verbose_name_plural': 'Sightings',
                'ordering': ['id_user'],
            },
        ),
    ]
