# Generated by Django 3.0.8 on 2022-03-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='TaxonomicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(max_length=100)),
                ('phylum', models.CharField(max_length=100)),
                ('t_class', models.CharField(max_length=100)),
                ('t_order', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'taxonomic_ategories',
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=100, unique=True)),
                ('pk_taxonomic_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='species_sighting_api.TaxonomicCategory')),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('author', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('sighting_date', models.DateTimeField(auto_now_add=True)),
                ('pk_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='species_sighting_api.Place')),
                ('pk_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_sighting_api.Specie')),
            ],
            options={
                'verbose_name_plural': 'sightings',
            },
        ),
    ]
