# Generated by Django 3.0.8 on 2022-03-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_sighting_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image_sighting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
