# Generated by Django 3.0.8 on 2022-03-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_sighting_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
