# Generated by Django 3.0.8 on 2022-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_sighting_api', '0002_auto_20220324_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
